baseURL: https://www.suriya.cc
disablePathToLower: true
languageCode: en-us
title: Suriya's site
params:
  author: Suriya Ganesh
  description: Suriya's blog of Stuff he dabbles with

module:
  imports:
  - path: hugomod

staticDir:
  - static

author:
  name: Suriya Ganesh
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0
  International License.

enableRobotsTXT: true
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false