baseURL: https://www.suriya.cc
disablePathToLower: true
languageCode: en-us
title: Suriya's site
params:
  author: Suriya Ganesh
  description: Suriya's blog of awesome stuff

module:
  imports:
  - path: hugomod

staticDir:
  - static

author:
  name: Suriya Ganesh
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0
  International License.
